Fix broken link in demo
PolymerElements/iron-icon pull request #106
Opened 2017-07-13 20:44 UTC by mikesteele

I encountered this broken link (and TODO) on the iron-icon webcomponents.org page. (https://www.webcomponents.org/element/PolymerElements/iron-icon/elements/iron-icon)

2017-07-13 20:45 UTC, mikesteele commented
I signed it!

2017-07-13 20:46 UTC, mikesteele commented
This PR also fixes #100

2017-07-26 05:13 UTC, stramel commented on demo/index.html
> +      <a href="/PolymerElements/iron-icons/v2.0.0/iron-icons/demo/index.html">&lt;iron-icons&gt;
this needs to be `/element/PolymerElements/iron-icons/demo/demo/index.html`

2017-07-26 05:14 UTC, stramel requested changes
this needs to be `/element/PolymerElements/iron-icons/demo/demo/index.html`

2017-07-26 15:21 UTC, mikesteele commented
@stramel Fixed, please re-review.

2017-07-26 15:38 UTC, stramel approved these changes

2017-07-26 15:38 UTC, stramel commented
LGTM! :+1: 

@e111077 or @bicknellr  Would you be kind enough to merge this?

2017-07-26 17:09 UTC, bicknellr requested changes

2017-07-26 17:09 UTC, bicknellr commented on demo/index.html
> +      <a href="/element/PolymerElements/iron-icons/demo/demo/index.html">&lt;iron-icons&gt;
The demos there are hosted in a different domain so you'll need to use the full URL. Also, I think this link needs `target="_top"` to prevent nesting inside the demo iframe.

@samuelli, is this the right way to link between demos on webcomponents.org?

2017-07-26 17:27 UTC, samuelli commented on demo/index.html
> +      <a href="/element/PolymerElements/iron-icons/demo/demo/index.html">&lt;iron-icons&gt;
You'd need a full URL there, since its in a different repo and inside a demo.

2017-07-26 17:29 UTC, mikesteele commented on demo/index.html
> +      <a href="/element/PolymerElements/iron-icons/demo/demo/index.html">&lt;iron-icons&gt;
So https://www.webcomponents.org/element/PolymerElements/iron-icons/demo/demo/index.html ?

2017-07-26 17:32 UTC, mikesteele commented on demo/index.html
> +      <a href="/element/PolymerElements/iron-icons/demo/demo/index.html">&lt;iron-icons&gt;
@samuelli And do you know if the link needs `target="_top"` ?

2017-07-26 17:37 UTC, samuelli commented on demo/index.html
> +      <a href="/element/PolymerElements/iron-icons/demo/demo/index.html">&lt;iron-icons&gt;
Yep, it does.

2017-07-26 17:41 UTC, mikesteele commented on demo/index.html
> +      <a href="/element/PolymerElements/iron-icons/demo/demo/index.html">&lt;iron-icons&gt;
Done! Please re-review @bicknellr & @samuelli

2017-07-26 17:58 UTC, stramel approved these changes

2017-07-26 18:32 UTC, bicknellr approved these changes

2017-07-26 18:36 UTC, merged