2.0-preview branch
PolymerElements/iron-icon pull request #80
Opened 2016-09-12 23:58 UTC by bicknellr

2017-03-29 21:10 UTC, notwaldorf approved these changes

2017-03-29 21:13 UTC, notwaldorf requested changes
The demo doesn't seem to work:

http://polygit.org/polymer+v2.0.0-rc.3/webcomponentsjs+webcomponents+v1.0.0-rc.6/shadycss+webcomponents+1.0.0-rc.2/paper*+polymerelements+:2.0-preview/iron*+polymerelements+:2.0-preview/app*+polymerelements+:2.0-preview/neon*+polymerelements+:2.0-preview/components/iron-icon/demo/index.html

2017-03-30 18:30 UTC, notwaldorf approved these changes

2017-03-30 18:30 UTC, notwaldorf commented
Ok demo is finally locally. 👍

2017-04-03 21:23 UTC, bicknellr commented on iron-icon.html
> +        fill: var(--iron-icon-fill-color, currentColor);
Looks like this change isn't necessary and `currentcolor` (w/o caps) might be the canonical spelling now, given [the note in this spec section](https://drafts.csswg.org/css-color/#currentcolor-color).

2017-04-04 21:03 UTC, notwaldorf requested changes

2017-04-04 21:03 UTC, notwaldorf commented on iron-icon.html
> +        fill: var(--iron-icon-fill-color, currentColor);
Cool, please revert then

2017-04-10 21:59 UTC, bicknellr commented on iron-icon.html
> +        fill: var(--iron-icon-fill-color, currentColor);
reverted

2017-04-12 05:58 UTC, e111077 requested changes

2017-04-12 05:58 UTC, e111077 commented on iron-icon.html
> +        @apply --layout-inline;
This is overriding `<iron-icon hidden>` see: https://github.com/PolymerLabs/note-app-elements/pull/7#discussion-diff-111049945R55

2017-04-14 01:34 UTC, notwaldorf commented
What's up with the tests failing? :(

2017-04-14 16:57 UTC, notwaldorf commented
@bicknellr without looking too much into it, i think the tests are timing out because of this import that doesn't exist (https://github.com/PolymerElements/iron-icon/blob/2.0-preview/test/iron-icon.html#L27), and i've _just_ hit this problem in a different repo -- basically if you do an import for a file you don't have, the tests don't run

2017-04-14 18:47 UTC, bicknellr commented
@notwaldorf Thanks for catching this! I'm sure that took forever to track down.

2017-04-14 18:47 UTC, bicknellr commented on iron-icon.html
> +        @apply --layout-inline;
Just added a `:host([hidden])` rule below that should handle this.

2017-04-14 18:48 UTC, e111077 approved these changes

2017-04-14 20:03 UTC, notwaldorf commented on iron-icon.html
> +        display: none;
ugh this may need !important

2017-04-14 20:03 UTC, notwaldorf approved these changes

2017-04-14 23:20 UTC, bicknellr commented on iron-icon.html
> +        display: none;
This slope's getting more slippery. :)

2017-04-14 23:52 UTC, bicknellr commented on iron-icon.html
> +        display: none;
Should I add this?

2017-05-12 20:59 UTC, merged